// THROWAWAY spike #1b — hand-written C++/JSI method bodies over the Rust C ABI.
// Marshals jsi values by hand; calls extern "C" lumi_* (cbindgen lumi_ffi.h).
// §1: only handle/publicKey/plaintext/ciphertext cross; no secret type appears.
#include "LumiCryptoImpl.h"

#include <cstdint>
#include <stdexcept>
#include <string>
#include <vector>

// cbindgen header (generated by scripts/build-rust-android.sh). cpp_compat=true in
// cbindgen.toml already wraps the decls in extern "C".
#include "lumi_ffi.h"

namespace facebook::react {

namespace {

constexpr char kB64[] =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

std::string base64Encode(const uint8_t *data, size_t len) {
  std::string out;
  out.reserve(((len + 2) / 3) * 4);
  size_t i = 0;
  while (i + 3 <= len) {
    uint32_t n = (data[i] << 16) | (data[i + 1] << 8) | data[i + 2];
    out.push_back(kB64[(n >> 18) & 63]);
    out.push_back(kB64[(n >> 12) & 63]);
    out.push_back(kB64[(n >> 6) & 63]);
    out.push_back(kB64[n & 63]);
    i += 3;
  }
  if (len - i == 1) {
    uint32_t n = data[i] << 16;
    out.push_back(kB64[(n >> 18) & 63]);
    out.push_back(kB64[(n >> 12) & 63]);
    out.push_back('=');
    out.push_back('=');
  } else if (len - i == 2) {
    uint32_t n = (data[i] << 16) | (data[i + 1] << 8);
    out.push_back(kB64[(n >> 18) & 63]);
    out.push_back(kB64[(n >> 12) & 63]);
    out.push_back(kB64[(n >> 6) & 63]);
    out.push_back('=');
  }
  return out;
}

int b64val(char c) {
  if (c >= 'A' && c <= 'Z') return c - 'A';
  if (c >= 'a' && c <= 'z') return c - 'a' + 26;
  if (c >= '0' && c <= '9') return c - '0' + 52;
  if (c == '+') return 62;
  if (c == '/') return 63;
  return -1;
}

std::vector<uint8_t> base64Decode(const std::string &s) {
  std::vector<uint8_t> out;
  out.reserve((s.size() / 4) * 3);
  int buf = 0, bits = 0;
  for (char c : s) {
    if (c == '=' || c == '\n' || c == '\r' || c == ' ') continue;
    int v = b64val(c);
    if (v < 0) throw std::runtime_error("invalid base64");
    buf = (buf << 6) | v;
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      out.push_back(static_cast<uint8_t>((buf >> bits) & 0xFF));
    }
  }
  return out;
}

uint64_t parseHandle(jsi::Runtime &rt, const std::string &h) {
  try {
    return std::stoull(h);
  } catch (...) {
    throw jsi::JSError(rt, "invalid handle: " + h);
  }
}

} // namespace

LumiCrypto::LumiCrypto(std::shared_ptr<CallInvoker> jsInvoker)
    : NativeLumiCryptoCxxSpec<LumiCrypto>(std::move(jsInvoker)) {}

jsi::Object LumiCrypto::newDeviceKey(jsi::Runtime &rt) {
  uint64_t handle = 0;
  uint8_t pub[32];
  int rc = lumi_new_device_key(&handle, pub);
  if (rc != LUMI_OK) {
    throw jsi::JSError(rt, "newDeviceKey failed (" + std::to_string(rc) + ")");
  }
  jsi::Object o(rt);
  o.setProperty(rt, "handle", jsi::String::createFromUtf8(rt, std::to_string(handle)));
  o.setProperty(rt, "publicKeyB64", jsi::String::createFromUtf8(rt, base64Encode(pub, 32)));
  return o;
}

std::string LumiCrypto::sealCheckin(
    jsi::Runtime &rt,
    std::string handle,
    std::string peerPublicB64,
    std::string mood,
    double intensity,
    std::string note) {
  uint64_t h = parseHandle(rt, handle);
  std::vector<uint8_t> peer = base64Decode(peerPublicB64);
  if (peer.size() != 32) {
    throw jsi::JSError(rt, "peerPublicB64 must decode to 32 bytes");
  }
  uint8_t *out = nullptr;
  size_t outLen = 0;
  int rc = lumi_seal_checkin(
      h, peer.data(), peer.size(), mood.c_str(),
      static_cast<uint8_t>(intensity), note.c_str(), &out, &outLen);
  if (rc != LUMI_OK) {
    throw jsi::JSError(rt, "sealCheckin failed (" + std::to_string(rc) + ")");
  }
  std::string b64 = base64Encode(out, outLen);
  lumi_free_buf(out, outLen);
  return b64;
}

jsi::Object LumiCrypto::openCheckin(
    jsi::Runtime &rt,
    std::string handle,
    std::string peerPublicB64,
    std::string sealedB64) {
  uint64_t h = parseHandle(rt, handle);
  std::vector<uint8_t> peer = base64Decode(peerPublicB64);
  std::vector<uint8_t> sealed = base64Decode(sealedB64);
  if (peer.size() != 32) {
    throw jsi::JSError(rt, "peerPublicB64 must decode to 32 bytes");
  }
  char *mood = nullptr;
  uint8_t intensity = 0;
  char *note = nullptr;
  int rc = lumi_open_checkin(
      h, peer.data(), peer.size(), sealed.data(), sealed.size(),
      &mood, &intensity, &note);
  if (rc != LUMI_OK) {
    // The throwing path: wrong key / tampered / garbage sealed blob.
    throw jsi::JSError(rt, "openCheckin failed (" + std::to_string(rc) + ")");
  }
  jsi::Object o(rt);
  o.setProperty(rt, "mood", jsi::String::createFromUtf8(rt, std::string(mood)));
  o.setProperty(rt, "intensity", jsi::Value(static_cast<double>(intensity)));
  o.setProperty(rt, "note", jsi::String::createFromUtf8(rt, std::string(note)));
  lumi_free_string(mood);
  lumi_free_string(note);
  return o;
}

} // namespace facebook::react
