// THROWAWAY spike #1b — hand-written C++ Nitro Hybrid Object impl over the Rust C
// ABI. Goes in the scaffolded library's `cpp/` dir (already on the CMake include
// path). Subclasses the Nitrogen-generated HybridLumiCryptoSpec. The OnLoad
// autolinking file does `#include "HybridLumiCrypto.hpp"` and requires a public
// zero-arg constructor (default-constructible) to register it.
#pragma once

#include <string>

// Generated by Nitrogen into nitrogen/generated/shared/c++ (on the include path via
// the +autolinking.cmake). Provides DeviceKey, CheckinDraft, HybridLumiCryptoSpec.
#include "HybridLumiCryptoSpec.hpp"

namespace margelo::nitro::lumicrypto {

class HybridLumiCrypto : public HybridLumiCryptoSpec {
 public:
  HybridLumiCrypto() : HybridObject(TAG) {}

  DeviceKey newDeviceKey() override;

  std::string sealCheckin(
      const std::string& handle,
      const std::string& peerPublicB64,
      const std::string& mood,
      double intensity,
      const std::string& note) override;

  CheckinDraft openCheckin(
      const std::string& handle,
      const std::string& peerPublicB64,
      const std::string& sealedB64) override;
};

} // namespace margelo::nitro::lumicrypto
