// THROWAWAY spike #1b — hand-written C++/JSI TurboModule impl over the Rust C ABI.
//
// INTEGRATION: create-react-native-library (--type turbo-module --languages cpp)
// generates a sample C++ TurboModule (a `multiply` method) plus the codegen base
// class `NativeLumiCryptoCxxSpec` (from NativeLumiCrypto.ts). Replace the generated
// class body with this one (or copy the 3 method decls in, drop `multiply`). Keep
// the constructor + base class exactly as the scaffold generated them; only the
// header name below may differ — match it to your generated spec header.
#pragma once

#include <memory>
#include <string>

#include <ReactCommon/TurboModule.h>
#include <jsi/jsi.h>

// Generated by RN codegen from NativeLumiCrypto.ts. The exact filename is produced
// in your scaffold's build/generated output — adjust if different.
#include <NativeLumiCryptoSpec.h>

namespace facebook::react {

class LumiCrypto : public NativeLumiCryptoCxxSpec<LumiCrypto> {
 public:
  explicit LumiCrypto(std::shared_ptr<CallInvoker> jsInvoker);

  jsi::Object newDeviceKey(jsi::Runtime &rt);

  std::string sealCheckin(
      jsi::Runtime &rt,
      std::string handle,
      std::string peerPublicB64,
      std::string mood,
      double intensity,
      std::string note);

  jsi::Object openCheckin(
      jsi::Runtime &rt,
      std::string handle,
      std::string peerPublicB64,
      std::string sealedB64);
};

} // namespace facebook::react
